// This file exports the same product data as your frontend, for use in the backend search API
export type Product = {
	id: number;
	name: string;
	description: string;
	price: number;
	image: string;
};

export const products: Product[] = [
	{
		id: 1,
		name: "AI T-Shirt",
		description: "A stylish t-shirt for AI enthusiasts.",
		price: 25.99,
		image: "https://picsum.photos/200/200?random=1",
	},
	{
		id: 2,
		name: "Smart Mug",
		description: "A mug that keeps your drink at the perfect temperature.",
		price: 39.99,
		image: "https://picsum.photos/200/200?random=2",
	},
	{
		id: 3,
		name: "Robot Toy",
		description: "A fun robot toy for all ages.",
		price: 49.99,
		image: "https://picsum.photos/200/200?random=3",
	},
	{
		id: 4,
		name: "Wireless Earbuds",
		description: "Noise-cancelling wireless earbuds with long battery life.",
		price: 79.99,
		image: "https://picsum.photos/200/200?random=4",
	},
	{
		id: 5,
		name: "Smart Watch",
		description: "Track your fitness and notifications on your wrist.",
		price: 129.99,
		image: "https://picsum.photos/200/200?random=5",
	},
	{
		id: 6,
		name: "Bluetooth Speaker",
		description: "Portable speaker with deep bass and clear sound.",
		price: 59.99,
		image: "https://picsum.photos/200/200?random=6",
	},
	{
		id: 7,
		name: "VR Headset",
		description: "Immersive virtual reality headset for gaming and media.",
		price: 199.99,
		image: "https://picsum.photos/200/200?random=7",
	},
	{
		id: 8,
		name: "Smart Light Bulb",
		description: "Color-changing LED bulb controllable by app.",
		price: 14.99,
		image: "https://picsum.photos/200/200?random=8",
	},
	{
		id: 9,
		name: "Fitness Tracker",
		description: "Monitor your steps, heart rate, and sleep.",
		price: 49.99,
		image: "https://picsum.photos/200/200?random=9",
	},
	{
		id: 10,
		name: "AI Notebook",
		description: "A notebook with built-in AI-powered search.",
		price: 19.99,
		image: "https://picsum.photos/200/200?random=10",
	},
	{
		id: 11,
		name: "Smart Thermostat",
		description: "Control your home's temperature from anywhere.",
		price: 149.99,
		image: "https://picsum.photos/200/200?random=11",
	},
	{
		id: 12,
		name: "Robot Vacuum",
		description: "Automatic vacuum cleaner with smart mapping.",
		price: 299.99,
		image: "https://picsum.photos/200/200?random=12",
	},
	{
		id: 13,
		name: "Wireless Charger",
		description: "Fast wireless charging pad for your devices.",
		price: 29.99,
		image: "https://picsum.photos/200/200?random=13",
	},
	{
		id: 14,
		name: "AI Pen",
		description: "A pen that digitizes your notes in real time.",
		price: 39.99,
		image: "https://picsum.photos/200/200?random=14",
	},
	{
		id: 15,
		name: "Smart Backpack",
		description: "Backpack with built-in USB charging port.",
		price: 59.99,
		image: "https://picsum.photos/200/200?random=15",
	},
	{
		id: 16,
		name: "Noise Cancelling Headphones",
		description: "Block out distractions with active noise cancellation.",
		price: 129.99,
		image: "https://picsum.photos/200/200?random=16",
	},
	{
		id: 17,
		name: "Smart Water Bottle",
		description: "Tracks your hydration and reminds you to drink.",
		price: 34.99,
		image: "https://picsum.photos/200/200?random=17",
	},
	{
		id: 18,
		name: "AI Desk Lamp",
		description: "Adjusts brightness and color temperature automatically.",
		price: 44.99,
		image: "https://picsum.photos/200/200?random=18",
	},
	{
		id: 19,
		name: "Portable Projector",
		description: "Mini projector for movies and presentations.",
		price: 179.99,
		image: "https://picsum.photos/200/200?random=19",
	},
	{
		id: 20,
		name: "Smart Plug",
		description: "Control any device with your voice or phone.",
		price: 12.99,
		image: "https://picsum.photos/200/200?random=20",
	},
	{
		id: 21,
		name: "AI Plant Pot",
		description: "Monitors and waters your plant automatically.",
		price: 49.99,
		image: "https://picsum.photos/200/200?random=21",
	},
	{
		id: 22,
		name: "Smart Mirror",
		description: "Displays weather, news, and your schedule.",
		price: 249.99,
		image: "https://picsum.photos/200/200?random=22",
	},
	{
		id: 23,
		name: "AI Mouse",
		description: "Ergonomic mouse with gesture controls.",
		price: 39.99,
		image: "https://picsum.photos/200/200?random=23",
	},
	{
		id: 24,
		name: "Smart Lock",
		description: "Keyless entry with fingerprint and app control.",
		price: 99.99,
		image: "https://picsum.photos/200/200?random=24",
	},
	{
		id: 25,
		name: "AI Speaker",
		description: "Voice assistant speaker for your smart home.",
		price: 89.99,
		image: "https://picsum.photos/200/200?random=25",
	},
	{
		id: 26,
		name: "Smart Fan",
		description: "WiFi-enabled fan with scheduling and remote control.",
		price: 59.99,
		image: "https://picsum.photos/200/200?random=26",
	},
	{
		id: 27,
		name: "AI Camera",
		description: "Security camera with AI motion detection.",
		price: 79.99,
		image: "https://picsum.photos/200/200?random=27",
	},
	{
		id: 28,
		name: "Smart Scale",
		description: "Tracks weight, BMI, and body composition.",
		price: 34.99,
		image: "https://picsum.photos/200/200?random=28",
	},
	{
		id: 29,
		name: "AI Keyboard",
		description: "Mechanical keyboard with customizable macros.",
		price: 69.99,
		image: "https://picsum.photos/200/200?random=29",
	},
	{
		id: 30,
		name: "Smart TV Stick",
		description: "Stream your favorite shows in 4K.",
		price: 49.99,
		image: "https://picsum.photos/200/200?random=30",
	},
	{
		id: 31,
		name: "AI Drone",
		description: "Camera drone with obstacle avoidance.",
		price: 399.99,
		image: "https://picsum.photos/200/200?random=31",
	},
	{
		id: 32,
		name: "Smart Alarm Clock",
		description: "Wake up with light, sound, and app control.",
		price: 29.99,
		image: "https://picsum.photos/200/200?random=32",
	},
	{
		id: 33,
		name: "AI Glasses",
		description: "Smart glasses with heads-up display.",
		price: 199.99,
		image: "https://picsum.photos/200/200?random=33",
	},
	{
		id: 34,
		name: "Smart Toothbrush",
		description: "Tracks brushing habits and gives feedback.",
		price: 39.99,
		image: "https://picsum.photos/200/200?random=34",
	},
	{
		id: 35,
		name: "AI Wallet",
		description: "Track your spending and manage cards with AI.",
		price: 59.99,
		image: "https://picsum.photos/200/200?random=35",
	},
	{
		id: 36,
		name: "Smart Pet Feeder",
		description: "Automatic feeder with app scheduling.",
		price: 79.99,
		image: "https://picsum.photos/200/200?random=36",
	},
	{
		id: 37,
		name: "AI Suitcase",
		description: "Self-following suitcase with GPS tracking.",
		price: 299.99,
		image: "https://picsum.photos/200/200?random=37",
	},
	{
		id: 38,
		name: "Smart Desk",
		description: "Height-adjustable desk with memory presets.",
		price: 399.99,
		image: "https://picsum.photos/200/200?random=38",
	},
	{
		id: 39,
		name: "AI Oven",
		description: "Smart oven with recipe suggestions.",
		price: 249.99,
		image: "https://picsum.photos/200/200?random=39",
	},
	{
		id: 40,
		name: "Smart Fridge",
		description: "Tracks groceries and suggests recipes.",
		price: 899.99,
		image: "https://picsum.photos/200/200?random=40",
	},
	{
		id: 41,
		name: "AI Bike",
		description: "Electric bike with route optimization.",
		price: 999.99,
		image: "https://picsum.photos/200/200?random=41",
	},
	{
		id: 42,
		name: "Smart Shoes",
		description: "Tracks steps and posture, connects to app.",
		price: 89.99,
		image: "https://picsum.photos/200/200?random=42",
	},
	{
		id: 43,
		name: "AI Coffee Maker",
		description: "Brew coffee with voice commands and scheduling.",
		price: 129.99,
		image: "https://picsum.photos/200/200?random=43",
	},
	{
		id: 44,
		name: "Smart Blinds",
		description: "Automate your window blinds with app control.",
		price: 99.99,
		image: "https://picsum.photos/200/200?random=44",
	},
	{
		id: 45,
		name: "AI Air Purifier",
		description: "Monitors air quality and adjusts automatically.",
		price: 149.99,
		image: "https://picsum.photos/200/200?random=45",
	},
	{
		id: 46,
		name: "Smart Doorbell",
		description: "Video doorbell with motion alerts.",
		price: 79.99,
		image: "https://picsum.photos/200/200?random=46",
	},
	{
		id: 47,
		name: "AI Fan",
		description: "Smart fan with voice and app control.",
		price: 49.99,
		image: "https://picsum.photos/200/200?random=47",
	},
	{
		id: 48,
		name: "Smart Camera",
		description: "Indoor camera with night vision and alerts.",
		price: 59.99,
		image: "https://picsum.photos/200/200?random=48",
	},
	{
		id: 49,
		name: "AI Projector",
		description: "Portable projector with AI image enhancement.",
		price: 229.99,
		image: "https://picsum.photos/200/200?random=49",
	},
	{
		id: 50,
		name: "Smart Scale Pro",
		description: "Advanced smart scale with app integration.",
		price: 59.99,
		image: "https://picsum.photos/200/200?random=50",
	},
];
